### ISSUE TITLE
python版本要求过高

### ISSUE THREAD

**Issue by ethan-phu** [danodic-dev/mkdocs-backlinks#1]
你好，我这版使用的是python3.8,你的插件是python3.9以上的版本要求，能支持低版本python呢？

**Comment by danodic** [comment]
It actually uses Python 3.10. This version may have a few things that break compatibility with Python 3.8, but I am not sure if I have used any of those features and my current distribution ships 3.10 by default.

If you project is using Pipenv, you can just checkout this repository into another folder and point your Pipefile to use this folder instead of a Python package. Something like this:
```
mkdocs-backlinks = {path = "/home/myuser/mkdocs-backlinks/"}
```

From there you can just make all the changes needed (like downgrading Python) and run a `pipenv install` from your project folder to update the local package.
